import json
import hashlib
from psycopg2 import extras

BATTLE_ATTRIBUTES = BATTLE_ATTRIBUTES = [
    "active_pokemon",
    "all_active_pokemons",
    "available_moves",
    "available_switches",
    "battle_tag",
    "can_dynamax",
    "can_mega_evolve",
    "can_tera",
    "can_z_move",
    "current_observation",
    "dynamax_turns_left",
    "fields",
    "finished",
    "force_switch",
    "format",
    "gen",
    "grounded",
    "in_team_preview",
    "last_request",
    "logger",
    "lost",
    "max_team_size",
    "maybe_trapped",
    "observations",
    "opponent_active_pokemon",
    "opponent_dynamax_turns_left",
    "opponent_rating",
    "opponent_role",
    "opponent_side_conditions",
    "opponent_team",
    "opponent_used_dynamax",
    "opponent_used_mega_evolve",
    "opponent_used_tera",
    "opponent_used_z_move",
    "opponent_username",
    "player_role",
    "player_username",
    "players",
    "rating",
    "reviving",
    "rules",
    "side_conditions",
    "team",
    "team_size",
    "teampreview",
    "teampreview_opponent_team",
    "teampreview_team",
    "trapped",
    "turn",
    "used_dynamax",
    "used_mega_evolve",
    "used_tera",
    "used_z_move",
    "weather",
    "won",
]

POKEMON_ATTRIBUTES = POKEMON_ATTRIBUTES = [
    "ability",
    "active",
    "available_z_moves",
    "base_species",
    "base_stats",
    "boosts",
    "current_hp",
    "current_hp_fraction",
    "effects",
    "fainted",
    "first_turn",
    "gender",
    "height",
    "is_dynamaxed",
    "is_terastallized",
    "item",
    "level",
    "max_hp",
    "moves",
    "must_recharge",
    "name",
    "original_types",
    "pokeball",
    "possible_abilities",
    "preparing",
    "preparing_move",
    "preparing_target",
    "protect_counter",
    "revealed",
    "shiny",
    "species",
    "stab_multiplier",
    "stats",
    "status",
    "status_counter",
    "tera_type",
    "type_1",
    "type_2",
    "types",
    "weight",
]


class State:
    def __init__(self,
                 battle_obj,
    ) -> None:
        self.battle_state: dict[str, str] = {attr: battle_obj.__getattribute__(attr).__str__() for attr in BATTLE_ATTRIBUTES}
        self.player_pokemon: dict[str, str] = {attr: battle_obj["active_pokemon"].__getattribute__(attr).__str__() for attr in POKEMON_ATTRIBUTES}
        self.opponent_pokemon: dict[str, str] = {attr: battle_obj["opponent_active_pokemon"].__getattribute__(attr).__str__() for attr in POKEMON_ATTRIBUTES}

        self.state_dict: dict[str, dict[str, str]] = {
            "battle_state": self.battle_state,
            "player_pokemon": self.player_pokemon,
            "opponent_pokemon": self.opponent_pokemon
        }

        self.hash = self.compute_state_hash()